# Generated by Django 5.1.3 on 2024-11-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='serving_restaurant',
        ),
        migrations.AddField(
            model_name='menu',
            name='serving_restaurant',
            field=models.ManyToManyField(to='restaurantapp.locations'),
        ),
    ]
