# Generated by Django 5.1.3 on 2024-11-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_alter_orders_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsordered',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemsordered',
            name='item_price_from_restaurant',
        ),
        migrations.RemoveField(
            model_name='itemsordered',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='itemsordered',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='itemsordered',
            name='veg_or_nonveg',
        ),
        migrations.AddField(
            model_name='itemsordered',
            name='menu_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='type',
            field=models.CharField(choices=[('starter', 'Starters'), ('drinks', 'Drinks'), ('biriyani', 'Biriyani')], max_length=20),
        ),
        migrations.AlterField(
            model_name='menu',
            name='veg_or_nonveg',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non Veg')], max_length=10),
        ),
    ]
