# Generated by Django 5.1.3 on 2024-11-20 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_remove_menu_serving_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='available',
        ),
        migrations.CreateModel(
            name='MenuAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.locations')),
            ],
        ),
    ]
