# Generated by Django 5.1.3 on 2024-11-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_remove_menu_available_menuavailable'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='reservation_token',
            field=models.CharField(default='it', max_length=15),
        ),
    ]
