# Generated by Django 5.1.3 on 2024-11-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_reservations_reservation_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='email',
            field=models.EmailField(max_length=90),
        ),
    ]
