# Generated by Django 5.1.3 on 2024-11-27 10:00

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_itemsordered_item_cancelled_itemsordered_quantity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orders',
            managers=[
                ('new_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
