# Generated by Django 5.1.3 on 2024-11-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_alter_orders_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='orders',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='bills',
            name='order_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.orders'),
        ),
        migrations.AlterField(
            model_name='itemsordered',
            name='menu_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menu'),
        ),
        migrations.AlterField(
            model_name='itemsordered',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_ordered', to='restaurantapp.orders'),
        ),
    ]
