# Generated by Django 5.1.3 on 2024-11-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0005_alter_restaurantuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='fullname',
            field=models.CharField(default='name', max_length=90),
        ),
    ]
