# Generated by Django 5.1.3 on 2024-12-01 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0008_reservations_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 9, 36, 35, 475016, tzinfo=datetime.timezone.utc)),
        ),
    ]
